export declare const copyToClipboard: (text: string) => Promise<void>;
export declare const isDateValid: (date: string) => boolean;
export declare const dayOfYear: (date: any) => number;
export declare const getLastDayOfMonth: (year: number, month: number, day: string) => any;
export declare const timeFromDate: (date: Date) => string;
export declare const capitalize: (str: string) => string;
export declare const dayDif: (start: any, end: any) => number;
export declare const clearCookies: () => void;
export declare const randomHex: () => string;
export declare const removeDuplicates: (arr: any[]) => any;
export declare const getQueryParams: (url: string) => string;
export declare const arrayToCSV: (arr: any[], delimiter?: string) => string;
export declare const average: (...nums: number[]) => number;
export declare const bottomVisible: () => boolean;
export declare const differenceTwoArrays: (a: any[], b: any[]) => any[];
export declare const getStyle: (el: any, ruleName: string) => any;
export declare const hasClass: (el: any, className: string) => any;
export declare const insertAfter: (el: any, htmlString: string) => any;
export declare const insertBefore: (el: any, htmlString: string) => any;
export declare const isBrowser: () => boolean;
export declare const isBrowserTabFocused: () => boolean;
export declare const randomIntArrayInRange: (min: number, max: number, n?: number) => any;
export declare const randomIntegerInRange: (min: number, max: number) => number;
export declare const randomNumberInRange: (min: number, max: number) => number;
export declare const redirectTo: (url: string, asLink?: boolean) => string | void;
export declare const reverseString: (str: any) => string;
export declare const sortArray: (arr: any[], key: string, orderBy?: string) => any[];
export declare const scrollToTop: () => void;
export declare const currentTime: () => string;
export declare const createTimer: (start: string, end: string) => {
    days: number;
    hours: number;
    minutes: number;
    seconds: number;
    expired: boolean;
} | {
    expired: boolean;
    days?: undefined;
    hours?: undefined;
    minutes?: undefined;
    seconds?: undefined;
};
